# Generated by Django 5.1 on 2024-09-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_mobile_number_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('quality', models.CharField(max_length=50)),
                ('image', models.URLField()),
            ],
        ),
    ]
