# Generated by Django 5.1 on 2024-09-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_movie_year_alter_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='genre',
        ),
    ]
