# Generated by Django 5.1 on 2024-09-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_webseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='webseries',
            name='image',
            field=models.ImageField(default=1, upload_to='web_series_images/'),
            preserve_default=False,
        ),
    ]
