# Generated by Django 5.1 on 2024-09-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_webseries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webseries',
            name='image',
            field=models.ImageField(upload_to='webseries_images/'),
        ),
    ]
