# Generated by Django 5.1 on 2024-09-14 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_webseries_duration_per_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webseries',
            name='duration_per_episode',
        ),
        migrations.RemoveField(
            model_name='webseries',
            name='episodes',
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(max_length=255)),
                ('episode_number', models.IntegerField()),
                ('duration', models.CharField(max_length=8)),
                ('release_date', models.DateField()),
                ('web_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.webseries')),
            ],
        ),
    ]
