# Generated by Django 5.1 on 2024-09-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_webseries_duration_per_episode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resolution', models.CharField(max_length=50)),
                ('supported_devices', models.CharField(max_length=255)),
                ('screens', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('extras', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
