# Generated by Django 5.1 on 2024-09-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
