# Generated by Django 5.1 on 2024-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_episode_season_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_image',
            field=models.ImageField(default=1, upload_to='episode_images/'),
            preserve_default=False,
        ),
    ]
