# Generated by Django 5.1 on 2024-09-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_episode_episode_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='release_year',
        ),
    ]
