# Generated by Django 5.1 on 2024-09-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_year_movie_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='last_name',
        ),
    ]
