# Generated by Django 5.1 on 2024-09-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='surname',
        ),
    ]
