# Generated by Django 5.1 on 2024-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_customer_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='film_industry',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
